import { Inter } from "next/font/google";
import Header from "@/components/header";
import { store } from "@/store/index";
import { fetchUser } from "@/store/user-store";
import "./globals.css";
import StoreProvider from "@/store/store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await store.dispatch(fetchUser());

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Header />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
